sudo: false

language: python

os:
  - linux
  - osx

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests

env:
  # code analysis
  - TASK=lint
  # build analysis
  - TASK=build

addons:
  apt:
    packages:
      - doxygen
      - wget
      - git
      - libcurl4-openssl-dev
      - unzip
      - libatlas-dev
      - libopencv-dev
      - gcc-4.8
      - g++-4.8
      - python-numpy
      - python-nose
      - python3-numpy
      - python3-dev
      - python3-nose
      - graphviz

before_install:
  - source scripts/travis/travis_setup_env.sh
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python

install:
  - source scripts/travis/setup.sh

script:
  - scripts/travis/run_test.sh

cache:
  directories:
    - ${HOME}/.cache/usr

before_cache:
  - scripts/travis/travis_before_cache.sh

after_failure:
  - scripts/travis/travis_after_failure.sh

notifications:
  email:
    on_success: change
    on_failure: always
